#!/usr/bin/with-contenv bash
set -x
if [[ $JVB_USE_PRIVATE_NET -eq 1 || x$JVB_USE_PRIVATE_NET == xtrue ]]; then
    if [ ! -f "$HOST_ETC/hostip" ]; then
        echo "can not find hostip file in host /etc. Exit ..."
        exit 1
    fi
    export PUBLIC_ADDRESS=$(cat $HOST_ETC/hostip | head -n 1 |  sed 's/ //g')
else
    export PUBLIC_ADDRESS=$(dig +short myip.opendns.com @resolver1.opendns.com +tcp)
fi

export LOCAL_ADDRESS=$(ip route get "$PUBLIC_ADDRESS" | head -n1 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')

if [[ -z $JVB_AUTH_PASSWORD ]]; then
    echo 'FATAL ERROR: JVB auth password must be set'
    exit 1
fi

OLD_JVB_AUTH_PASSWORD=passw0rd
if [[ "$JVB_AUTH_PASSWORD" == "$OLD_JVB_AUTH_PASSWORD" ]]; then
    echo 'FATAL ERROR: JVB auth password must be changed, check the README'
    exit 1
fi

[ -z "${XMPP_SERVER}" ] && export XMPP_SERVER=xmpp.meet.jitsi

# On environments like Swarm the IP address used by the default gateway need not be
# the one used for inter-container traffic. Use that one for our fallback ID.
XMPP_SERVER_IP=$(dig +short +search ${XMPP_SERVER})
export JVB_WS_SERVER_ID_FALLBACK=$(ip route get ${XMPP_SERVER_IP} | grep -oP '(?<=src ).*' | awk '{ print $1 '})

export SENTRY_RELEASE="${SENTRY_RELEASE:-$(apt-cache policy jitsi-videobridge2 | sed -n '/Installed/p' | sed -e 's/[^:]*: //')}"

if [[ -f /config/custom-sip-communicator.properties ]]; then
    cat /config/custom-sip-communicator.properties > /config/sip-communicator.properties
fi

tpl /defaults/sip-communicator.properties > /config/sip-communicator.properties
tpl /defaults/logging.properties > /config/logging.properties
tpl /defaults/jvb.conf > /config/jvb.conf

chown -R jvb:jitsi /config
